# Conda environment file for complete verifier with PyTorch 2.8.0 CUDA 12.8

# Created with the following command:
# conda create --name verifier_pyt280 python=3.11
# conda activate verifier_pyt280
# pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128
# conda install gurobi==12.0.0 -c gurobi
# conda install numpy protobuf pyyaml appdirs sortedcontainers packaging psutil tqdm pandas pytest pre-commit mpmath pygments rich scikit-learn scipy graphviz python-graphviz
# pip install onnx onnxruntime onnxoptimizer onnxsim skl2onnx
# pip install --no-deps git+https://github.com/Verified-Intelligence/onnx2pytorch.git

channels:
  - gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - adwaita-icon-theme=48.0=h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - at-spi2-atk=2.34.2=hfac8509_1
  - at-spi2-core=2.36.0=h597f2ad_2
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311haa0f9ac_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - cffi=2.0.0=py311h4eded50_1
  - cfgv=3.4.0=py311h06a4308_0
  - dbus=1.16.2=h5bd4931_0
  - distlib=0.4.0=py311hee96239_0
  - epoxy=1.5.4=h7f8727e_2
  - expat=2.7.3=h3385a95_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - gettext=0.21.0=hedfda30_2
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gobject-introspection=1.84.0=py311hcb37abf_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=12.2.1=h053244a_2
  - gtk3=3.24.21=h40e4fd3_8
  - gts=0.7.6=hb67d8dd_3
  - gurobi=12.0.0=py311_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hicolor-icon-theme=0.17=h06a4308_2
  - icu=73.1=h6a678d5_0
  - identify=2.5.5=py311h06a4308_0
  - iniconfig=2.1.0=py311h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - joblib=1.5.2=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libboost=1.88.0=h9d9b81f_0
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - librsvg=2.56.3=hb0330b6_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libtool=2.4.7=h6a678d5_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py311h06a4308_0
  - mdurl=0.1.2=py311h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.1=h06a4308_0
  - ninja-base=1.13.1=h0f57076_0
  - nodeenv=1.9.1=py311h06a4308_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numexpr=2.14.1=py311h41d4191_0
  - numpy-base=2.3.5=py311h00548fb_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py311h06a4308_1
  - pandas=2.3.3=py311h23c847b_1
  - pango=1.50.7=h668f713_2
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py311h06a4308_0
  - pluggy=1.5.0=py311h06a4308_0
  - poppler=24.09.0=h696634e_4
  - poppler-data=0.4.12=h06a4308_0
  - pre-commit=3.4.0=py311h06a4308_1
  - protobuf=6.33.0=py311hbdd6827_0
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - pygments=2.19.2=py311h06a4308_0
  - pytest=8.4.2=py311h06a4308_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - rich=14.2.0=py311h06a4308_0
  - scikit-learn=1.7.2=py311h505adc9_0
  - scipy=1.16.3=py311h33bc11c_0
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=py311h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py311h7040dfc_1
  - tzdata=2025b=h04d1e81_0
  - ukkonen=1.0.1=py311hdb19cb5_1
  - virtualenv=20.28.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxinerama=1.1.5=h50385e7_1
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - coloredlogs==15.0.1
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fsspec==2025.9.0
      - humanfriendly==10.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - ml-dtypes==0.5.4
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - onnx==1.19.1
      - git+https://github.com/Verified-Intelligence/onnx2pytorch@8afb2243fddd1a4732883f1e2959f7e83f8201c5#egg=onnx2pytorch
      - onnxoptimizer==0.3.13
      - onnxruntime==1.23.2
      - onnxsim==0.4.36
      - pillow==11.3.0
      - skl2onnx==1.19.1
      - sympy==1.14.0
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - triton==3.4.0
      - typing-extensions==4.15.0
      - --extra-index-url https://download.pytorch.org/whl/cu128
