channels:
  - gurobi
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - attrs=22.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli-python=1.0.9=py39h6a678d5_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - coloredlogs=15.0.1=py39h06a4308_1
  - cryptography=39.0.1=py39h9ce1e76_2
  - cudatoolkit=11.5.1=hcf5317a_9
  - exceptiongroup=1.0.4=py39h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gurobi=10.0.2=py39_0
  - humanfriendly=10.0=py39h06a4308_1
  - idna=3.4=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py39h06a4308_1
  - mdurl=0.1.0=py39h06a4308_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py39hc78ab66_1
  - numpy=1.25.0=py39h5f9d8c6_0
  - numpy-base=1.25.0=py39hb5e798b_0
  - onnx=1.13.1=py39h12ddb61_0
  - onnxconverter-common=1.13.0=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pandas=1.5.3=py39h417a72b_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.1.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - protobuf=3.20.3=py39h6a678d5_0
  - psutil=5.9.0=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytest=7.3.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.11.0=py3.9_cuda11.5_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0=py39h5eee18b_1
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py39h06a4308_0
  - rich=13.3.5=py39h06a4308_0
  - scikit-learn=1.2.2=py39h6a678d5_1
  - scipy=1.9.3=py39hf6e8229_2
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - skl2onnx=1.14.0=py39h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.1.0=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py39h06a4308_0
  - torchvision=0.12.0=py39_cu115
  - tqdm=4.65.0=py39hb070fc8_0
  - typing-extensions=4.6.3=py39h06a4308_0
  - typing_extensions=4.6.3=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - flatbuffers==23.5.26
      - git+https://github.com/Verified-Intelligence/onnx2pytorch@fe7281b9b6c8c28f61e72b8f3b0e3181067c7399#egg=onnx2pytorch
      - onnxoptimizer==0.3.13
      - onnxruntime==1.15.1
      - onnxsim==0.4.33
