# Conda environment file for alpha,beta-CROWN, with pytorch 2.7.0

# Created with the following script:
# conda create --name verifier_pyt270 python=3.11
# conda activate verifier_pyt270
# pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
# conda install gurobi -c gurobi
# conda install appdirs blas bottleneck brotli-python bzip2 ca-certificates certifi cffi cfgv charset-normalizer cuda-cudart cuda-cupti cuda-libraries cuda-nvrtc cuda-nvtx cuda-opencl cuda-runtime cuda-version distlib ffmpeg filelock freetype gmp gmpy2 gnutls gurobi identify idna iniconfig intel-openmp jinja2 joblib jpeg lame lcms2 ld_impl_linux-64 lerc libcublas libcufft libcufile libcurand libcusolver libcusparse libdeflate libffi libgcc-ng libgfortran-ng libgfortran5 libgomp libiconv libidn2 libjpeg-turbo libnpp libnvjitlink libnvjpeg libpng libprotobuf libstdcxx-ng libtasn1 libtiff libunistring libuuid libwebp-base llvm-openmp lz4-c markdown-it-py markupsafe mdurl mkl mkl-service mkl_fft mkl_random mpc mpfr mpmath ncurses nettle networkx nodeenv numexpr openh264 openjpeg openssl packaging pandas pillow pip platformdirs pluggy pre-commit psutil pybind11-abi pycparser pygments pysocks pytest python python-dateutil python-tzdata pytorch pytorch-cuda pytorch-mutex pytz pyyaml readline requests rich scikit-learn scipy setuptools six sortedcontainers sqlite sympy tbb threadpoolctl tk torchaudio torchtriton torchvision tqdm typing-extensions typing_extensions tzdata ukkonen urllib3 virtualenv wheel xz yaml zlib zstd coloredlogs python-flatbuffers fsspec graphviz python-graphviz humanfriendly protobuf -c nvidia -c pytorch
# pip install onnx==1.17.0 onnxruntime onnxoptimizer onnxsim skl2onnx
# pip install --no-deps git+https://github.com/Verified-Intelligence/onnx2pytorch.git
#
# Then replace the line with onnx2pytorch with:
# git+https://github.com/Verified-Intelligence/onnx2pytorch@8447c42c3192dad383e5598edc74dddac5706ee2#egg=onnx2pytorch
# and add the extra-index-url line: --extra-index-url https://download.pytorch.org/whl/cu128

channels:
  - pytorch
  - gurobi
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.4.26=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - cfgv=3.4.0=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - coloredlogs=15.0.1=py311h06a4308_3
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - distlib=0.3.8=py311h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.0=hcdf2ecd_0
  - filelock=3.17.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2025.3.2=py311he3bba80_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.8.7=h532247a_0
  - gobject-introspection=1.78.1=py311h42194e9_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - gtk2=2.24.33=h27e1c3a_3
  - gts=0.7.6=hb67d8dd_3
  - gurobi=12.0.2=py311_0
  - harfbuzz=10.2.0=hf296adc_0
  - humanfriendly=10.0=py311h06a4308_2
  - icu=73.1=h6a678d5_0
  - identify=2.5.5=py311h06a4308_0
  - idna=3.7=py311h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.0.30=4
  - libcurand=10.3.10.19=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h536bbd8_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.9.19=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=hc99497a_0
  - librsvg=2.56.3=hf6914bd_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.4.7=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mdurl=0.1.0=py311h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py311h5eee18b_0
  - mkl_fft=1.3.1=py311h30b3d60_0
  - mkl_random=1.2.2=py311hba01205_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nodeenv=1.9.1=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py311h802d673_0
  - numpy=1.24.3=py311hc206e33_0
  - numpy-base=1.24.3=py311hfd5febd_0
  - ocl-icd=2.3.2=h5eee18b_1
  - onnx=1.17.0=py311he36ed58_2
  - onnxconverter-common=1.14.0=py311h06a4308_0
  - onnxruntime=1.20.1=py311hce09735_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pango=1.50.7=h0fee60c_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py311h06a4308_0
  - pluggy=1.5.0=py311h06a4308_0
  - pooch=1.8.2=py311h06a4308_0
  - poppler=24.09.0=hc52b300_2
  - poppler-data=0.4.11=h06a4308_1
  - pre-commit=3.4.0=py311h06a4308_1
  - protobuf=5.29.3=py311he621ea3_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - pytest=8.3.4=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-flatbuffers=24.3.25=py311h06a4308_0
  - python-graphviz=0.20.1=py311h06a4308_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - rich=13.9.4=py311h06a4308_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.10.1=py311hc206e33_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=py311h06a4308_0
  - skl2onnx=1.16.0=py311h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.1.0=py311
  - tqdm=4.67.1=py311h92b7b1e_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ukkonen=1.0.1=py311hdb19cb5_1
  - urllib3=2.3.0=py311h06a4308_0
  - virtualenv=20.28.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - mpmath==1.3.0
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - git+https://github.com/Verified-Intelligence/onnx2pytorch@8afb2243fddd1a4732883f1e2959f7e83f8201c5#egg=onnx2pytorch
      - onnxoptimizer==0.3.13
      - onnxsim==0.4.36
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - triton==3.3.0
      - --extra-index-url https://download.pytorch.org/whl/cu128
